name: CI/CD Maven Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Maven build
        uses: ./.github/actions/maven-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JAR to S3
        run: |
          aws s3 cp target/spring-boot-todo-crud-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET }}/app.jar

      - name: Deploy to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo systemctl stop springboot || true",
              "sudo mkdir -p /home/ssm-user/Maven-springboot-todo",
              "sudo chown -R ssm-user:ssm-user /home/ssm-user/Maven-springboot-todo",
              "aws s3 cp s3://${{ secrets.S3_BUCKET }}/app.jar /home/ssm-user/Maven-springboot-todo/spring-boot-todo-crud-0.0.1-SNAPSHOT.jar",
              "sudo systemctl start springboot"
            ]' \
            --region ${{ secrets.AWS_REGION }}
